app.menus:
  - title: Home
    name: Home
    path: /
  - title: Login
    name: Login
    path: /login
spring:
  mustache:
    expose-request-attributes: true
    suffix: .html
logging:
  level:
    org.springframework.security: DEBUG
app:
  services:
    resource: http://localhost:9000