app.menus:
  - title: Home
    name: Home
    path: /
  - title: Login
    name: Login
    path: /login
spring:
  mustache:
    expose-request-attributes: true
logging:
  level:
    org.springframework.security: DEBUG